name: 'regional_bank_data_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'regional_bank'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  regional_bank_data_platform:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    intermediate:
      +materialized: view
      +schema: intermediate
    core:
      +materialized: table
      +schema: core

# Configuring seeds
seeds:
  regional_bank_data_platform:
    +schema: raw
    country_codes:
      +column_types:
        country_code: varchar(3)
        country_name: varchar(100)
    sector_codes:
      +column_types:
        sector_code: varchar(10)
        sector_name: varchar(100)
        sector_category: varchar(50)

# Configuring tests
tests:
  regional_bank_data_platform:
    +store_failures: true
    +severity: warn

# Configuring snapshots
snapshots:
  regional_bank_data_platform:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: last_updated

# Configuring documentation
docs-paths: ["docs"]

# Configuring packages
packages-install-path: "dbt_packages"

# Configuring vars
vars:
  # Data quality thresholds
  null_threshold: 0.1
  duplicate_threshold: 0.05
  
  # Business logic constants
  high_value_transaction_threshold: 100000
  large_remittance_threshold: 50000
  
  # Date ranges
  lookback_days: 30
  forecast_days: 90
