name: 'regional_bank_demo'
version: '1.0.0'
config-version: 2
profile: 'regional_bank_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  regional_bank_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: view

vars:
  null_threshold: 0.1
  duplicate_threshold: 0.05
  high_value_transaction_threshold: 100000
  large_remittance_threshold: 50000
